version: 1.5.0.{build}

environment:
  DOXYGEN: 1.8.14
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
    BOOST: C:\Libraries\boost_1_69_0
    BOOST_LIB: C:\Libraries\boost_1_69_0\lib64-msvc-14.1
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
    BOOST: C:\Libraries\boost_1_71_0
    BOOST_LIB: C:\Libraries\boost_1_71_0\lib64-msvc-14.2

install:
- cmd: >-
    cd C:\Tools\vcpkg

    git pull --quiet

    bootstrap-vcpkg.bat

    vcpkg --triplet x64-windows-static install cryptopp curl openssl pbc nlohmann-json

    vcpkg upgrade --no-dry-run

    cd %APPVEYOR_BUILD_FOLDER%

    nuget install Doxygen -version %DOXYGEN% -outputdirectory ..

    git submodule update --init --recursive

cache: C:\Tools\vcpkg\installed

build_script:
- cmd: >-
    call "%VCVARS%"

    cmake -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\DCore -DCMAKE_PROGRAM_PATH=%APPVEYOR_BUILD_FOLDER%\..\Doxygen.%DOXYGEN%\tools -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBOOST_ROOT=%BOOST% -DBOOST_LIBRARYDIR=%BOOST_LIB% -DPYTHON_VERSION=37 -G Ninja .

    ninja -j2 install

    7z a DCore-python3.zip DCore\*

artifacts:
- path: DCore-python3.zip
  name: Module

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
